version: '2'

services:
  php:
    build: php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
      - db
  db:
    image: mysql:5.6.26
    ports:
      - "3306:3306"
#    volumes:
#      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passtoor
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
