version: '2'
services:
  web:
    image: fpfis/php56
    container_name: php_${BUILD_ID_UNIQUE}
    environment:
      DOCROOT: "${env.WORKSPACE}/platform"
    volumes:
      - ${env.WORKSPACE}:${env.WORKSPACE}
    working_dir: ${env.WORKSPACE}
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.6
    container_name: sql_${BUILD_ID_UNIQUE}
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: starterkit
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - '3306'
  #redis:
  #  image: fpfis/redis
  #varnish:
  #  image: fpfis/nexteuropa-varnish5
  solr:
    # The following cores are available :
    # - http://127.0.0.1:8983/solr/d7_search_api
    # - http://127.0.0.1:8983/solr/d7_apachesolr
    image: fpfis/solr5
    container_name: sol_${BUILD_ID_UNIQUE}
  selenium:
    image: selenium/standalone-chrome
    container_name: sel_${BUILD_ID_UNIQUE}

