version: '2'

services:
  php:
    build: php5.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - platform:/var/www/html
    links:
      - db
  db:
    image: mysql:5.6
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
